name: IoT Sensor Monitoring

on:
  # 라즈베리파이 데이터 수신용 (기존 유지)
  repository_dispatch:
    types: [sensor-data]
  # 스케줄 실행용 (기존 유지)
  schedule:
    - cron: '0 15 * * *'
  # [새로 추가] GitHub Actions 페이지에서 수동으로 실행할 수 있게 하는 트리거
  workflow_dispatch:

jobs:
  # 데이터 처리 작업
  process-sensor-data:
    # "if" 조건을 수정하여 수동 실행 시에는 이 작업이 실행되지 않도록 함
    if: github.event_name == 'repository_dispatch' || github.event_name == 'schedule'
    permissions:
      contents: write
      issues: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install requests
      - name: Process Data and Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENSOR_DATA: ${{ github.event.client_payload.data }}
        run: python ./scripts/process_data.py
      - name: Commit data files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update sensor data backup" && git push

  # 알림 초기화 작업
  clear-alerts:
    # "if" 조건을 수정하여 수동 실행(workflow_dispatch) 시에만 이 작업이 실행되도록 함
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close all alert issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue list --label "alert" --state "open" --json number --jq '.[].number' | xargs -I {} gh issue close {}
          echo "All alert issues have been closed."
